{
 "title": "Examine Specific Quabo",
 "description": "Inspect a single Quabo's metadata.",
 "tags": [ "Quabo" ],
 "time": { "from": "now-2y", "to": "now-1y" },
 "templating": {
  "list": [
   {
    "name": "quabo",
    "label": "Quabo ",
    "query": "SHOW MEASUREMENTS ON \"metadata\" WHERE \"observatory\" = '$observatory' "
   },
   {
    "name": "observatory",
    "label": "Observatory",
    "query": "SHOW TAG VALUES ON \"metadata\"  WITH KEY = \"observatory\""
   }
  ]
 },
 "panels": [
  {
   "title": "Status Information",
   "type": "state-timeline",
   "description": "Status timeline of Light Sensor Status, Shutter Status, and \"Start Up\".",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Light Sensor Status",
     "query": "SELECT last(\"LIGHT_SENSOR_STATUS\") FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval)"
    },
    {
     "alias": "Shutter Status",
     "query": "SELECT last(\"SHUTTER_STATUS\") FROM \"$quabo\" WHERE  \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) "
    },
    {
     "alias": "Start Up",
     "query": "SELECT last(\"StartUp\") FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Static Quabo Info",
   "type": "stat",
   "description": "Static information about $quabo.",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UID",
     "query": "SELECT UID FROM \"$quabo\" WHERE \"observatory\" = '$observatory'"
    },
    {
     "alias": "Board Loc",
     "query": "SELECT BOARDLOC FROM \"$quabo\"  WHERE \"observatory\" = '$observatory' "
    },
    {
     "query": "SELECT PCBREV_N FROM \"$quabo\" WHERE \"observatory\" = '$observatory' "
    },
    {
     "query": "SELECT FWVER FROM \"$quabo\" WHERE \"observatory\" = '$observatory' "
    }
   ]
  },
  { "title": "Detector info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Detector High Voltage and Quabo temperature",
   "type": "timeseries",
   "description": "HVMONx is the bias voltage to detector array x",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "HVMON0",
     "query": "SELECT last(HVMON0) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "HVMON1",
     "query": "SELECT last(HVMON1) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "HVMON2",
     "query": "SELECT last(HVMON2) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "HVMON3",
     "query": "SELECT last(HVMON3) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Detector Current Draw",
   "type": "timeseries",
   "description": "HVIMONx is the current drawn by detector array x",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "nA" } },
   "targets": [
    {
     "alias": "HVIMON0",
     "query": "SELECT last(HVIMON0) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "HVIMON1",
     "query": "SELECT last(HVIMON1) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "HVIMON2",
     "query": "SELECT last(HVIMON2) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "HVIMON3",
     "query": "SELECT last(HVIMON3) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "VCCx and VxMON",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "VCCAUX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "VCCAUX",
       "query": "SELECT last(VCCAUX) FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "VCCINT ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "VCCINT",
       "query": "SELECT last(VCCINT) FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "V12MON",
     "type": "timeseries",
     "description": "The voltage of the 1.2v supply to the FPGA MGT",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V12MON",
       "query": "SELECT last(V12MON) FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "V18MON",
     "type": "timeseries",
     "description": "The voltage of the 1.8v supply to the MAROCs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V18MON",
       "query": "SELECT last(V18MON) FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "V33MON",
     "type": "timeseries",
     "description": "The voltage of the 3.3v supply to the MAROCs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V33MON",
       "query": "SELECT last(V33MON) FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "V37MON",
     "type": "timeseries",
     "description": "The voltage of the 3.7v switching supply",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V37MON",
       "query": "SELECT last(V37MON) FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "IxMON",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "I10MON",
     "type": "timeseries",
     "description": "Current of the 1.0v supply to the FPGA core",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "uA" } },
     "targets": [
      {
       "alias": "I10MON",
       "query": "SELECT last(I10MON) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "I18MON",
     "type": "timeseries",
     "description": "Current of the 1.8v supply to the FPGA",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "uA" } },
     "targets": [
      {
       "alias": "I18MON",
       "query": "SELECT last(I18MON) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "I33MON",
     "type": "timeseries",
     "description": "Current of the 3.3v supply to the FPGA",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "uA" } },
     "targets": [
      {
       "alias": "I33MON",
       "query": "SELECT last(I33MON) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    }
   ]
  }
 ]
}