{
 "title": "Observatory Home",
 "description": "Display general status information about a PANOSETI observatory.",
 "tags": [
  "Overview",
  "Home"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "observatory",
    "label": "Observatory",
    "query": "SHOW TAG VALUES ON \"metadata\"  WITH KEY = \"observatory\""
   }
  ]
 },
 "panels": [
  {
   "title": "Last Quabo Temperature",
   "type": "stat",
   "description": "Last Quabo TEMP1\nin the interval: ${__from:date:iso} to ${__to:date:iso}. A dark red screen indicates that no Quabo data exists for the chosen time interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(TEMP1) FROM /QUABO_?.*/ WHERE \"observatory\" = '$observatory'  AND $timeFilter GROUP BY time($__interval), \"UID\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Time and Synchonization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "White Rabbit SoftPLL Status",
   "type": "state-timeline",
   "description": "Timeline of SOFTPLL status for each active WRS.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$measurement",
     "query": "SELECT last(\"SOFTPLL\") FROM /WRSWITCH.*/ WHERE \"observatory\" = '$observatory' AND \"datatype\" = 'whiterabbit' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "GPS Receiver Status",
   "type": "state-timeline",
   "description": "Timeline of GPS Status metadata.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "alias": "Receiver Mode",
     "query": "SELECT last(RECEIVERMODE) FROM GPSSUPP \nWHERE \"observatory\" = '$observatory' AND \"datatype\" = 'GPS' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Decoding Status",
     "query": "SELECT last(GPSDECODINGSTATUS) FROM GPSSUPP WHERE  \"observatory\" = '$observatory' AND \"datatype\" = 'GPS' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Disciplining Mode",
     "query": "SELECT last(DISCIPLININGMODE) FROM GPSSUPP WHERE  \"observatory\" = '$observatory' AND \"datatype\" = 'GPS' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Disciplining Activity",
     "query": "SELECT last(DISCIPLININGACTIVITY) FROM GPSSUPP WHERE  \"observatory\" = '$observatory' AND \"datatype\" = 'GPS' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}